import axios from 'axios';
import { NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import buildClient from '../util/build-client';
import BooksList from '../components/books-list/books-list.component';
import styles from '../styles/Home.module.scss';
import { Book } from './search';
import { BACKEND_URL } from './_app';

type HomePageProps = {
  mostLikedBooks: Book[];
};

const Home: NextPage<HomePageProps> = ({}) => {
  const [mostLikedBooks, setMostLikedBooks] = useState<Book[]>([]);
  const fetchData = async () => {
    const [{ data: mostLikedBooksData }] = await Promise.all([
      await axios.get(`${BACKEND_URL}/book/likes/mostliked`),
    ]);
    setMostLikedBooks(mostLikedBooksData.books);
  };
  useEffect(() => {
    fetchData();
  }, []);
  return (
    <>
      <Head>
        <title>Creates Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home_page_wrapper}>
        <div className={styles.home_page_container}>
          <BooksList books={mostLikedBooks} listTitle="most liked books" />
        </div>
      </div>
    </>
  );
};
export default Home;

// export async function getServerSideProps(context: NextPageContext) {
//   const client = buildClient(context);

//   const [{ data: mostLikedbooks }] = await Promise.all([
//     await client.get(`${BACKEND_URL}/book/likes/mostliked`),
//   ]);

//   return {
//     props: {
//       mostLikedBooks: mostLikedbooks.books,
//     },
//   };
// }
